### ISSUE TITLE
Reverse 32bit Integer number 

### ISSUE THREAD

**Issue by SiSaR-Pal** [MIT-Emerging-Talent/ET6-foundations-group-26#18]
# Reverse Integer

Given a signed 32-bit integer `x`, return `x` with its digits reversed. If reversing `x` causes the value to go outside the signed 32-bit integer range `[-2^31, 2^31 - 1]`, then return `0`. Assume the environment does not allow you to store 64-bit integers (signed or unsigned).

## Examples

- **Example 1:**
  - **Input:** `x = 123`
  - **Output:** `321`

- **Example 2:**
  - **Input:** `x = -123`
  - **Output:** `-321`

- **Example 3:**
  - **Input:** `x = 120`
  - **Output:** `21`

## Constraints:
- `-2^31 <= x <= 2^31 - 1`

**Comment by Nada-saad635** [comment]
Hi Said can make a pull request and push changes to the branch to review it

**Comment by SiSaR-Pal** [comment]
@Nada-saad635 I made some modification to the test file, and now it failed the CI checks,   py_formatting
I'm working on it

**Comment by Nada-saad635** [comment]
Hi Said try ruff format solutions\tests\test_reverse_integer.py

**Comment by Nada-saad635** [comment]
and so on for ruff format solutions\reverse_integer.py
