### ISSUE TITLE
communication

### ISSUE THREAD

**Issue by AseelOmer** [MIT-Emerging-Talent/ET6-foundations-group-26#2]
The communication plan needs to be updated to reflect the latest changes in the team schedule and channels. This involves:
- Adding new communication channels
- Updating the schedule for meetings
- Clarifying the roles of team members

**Comment by Nada-saad635** [comment]
seems good ! nice work

**Comment by CaesarGhazi** [comment]
i'm all for it!! GREAT WORK!
