### ISSUE TITLE
Third meeting agenda 

### ISSUE THREAD

**Issue by AseelOmer** [MIT-Emerging-Talent/ET6-foundations-group-26#9]
This meeting focuses on reflecting on what was missing in the past week, reviewing each member's progress on assigned tasks, setting crucial deadlines for ongoing tasks, and discussing the functions and problem statements the group is working on solving.

- [x] Reflection on Last Week:
     - Each team member shares what they felt was missing or needed improvement during the previous week

- [x] Progress Updates:
   - Each team member provides a brief update on the tasks they were assigned and their current status.

- [x] Task Deadlines (IMPORTANT):
   -  Discuss and set deadlines for all ongoing and upcoming tasks.

- [x] Challenges and Problem Statements
   - Discuss the functions and problem statements the group is tackling.
   -  Review progress and brainstorm approaches to solve these challenges
 
- [x] Explaining GitHub Workflow:
    - Demonstrate how to create an issue on GitHub and link it to a branch.
    - Explain how to make a pull request (PR) and link it to a branch.
    - Discuss how the PR moves automatically to the project board and the benefits of using this workflow in the project.

Date:
Saturday, 28th December 2024, 7:00 PM GMT+2

Let me know if there’s anything to add or revise in the comments!

**Comment by AseelOmer** [comment]
@CaesarGhazi @Nada-saad635 @omniaNS @Sufi-to @Elshikh-Amro @SiSaR-Pal @heba3 @Abeerdrar

**Comment by Nada-saad635** [comment]
good job Aseel can you add 
 review Things to Explain assignment 
 or you include it with last week ... ?what you think ?
another thing fix GitHub issues ?
 what you think ?

**Comment by AseelOmer** [comment]
sure thing will add that
